4:
  url: http://opensource.adobe.com/wiki/display/flexsdk/Download+Flex+4
3:
  url: http://opensource.adobe.com/wiki/display/flexsdk/Download+Flex+3
Hero:
  url: http://opensource.adobe.com/wiki/display/flexsdk/Download+Flex+Hero